name: Deploy

on:
  push:
    branches: [ alpine ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.2.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build image
        run: docker build -t drewdavis418/java-autograder:alpine .

      - name: Deploy to Docker Hub
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u drewdavis418 -p $DOCKER_PASS
          docker push purduecsbridge/java-autograder:alpine

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.2.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://hub.docker.com/repository/docker/drewdavis418/java-autograder/tags
